### ISSUE TITLE
adding another key to dictionary of the data field

### ISSUE THREAD

**Issue by XeBoris** [XENONnT/xenon_runsDB_api#3]
The current definition for the data field regarding Rucio entries holds:
  * location
  * status
  * host
  * type
  * meta
  * rse
  * destination

Can we add the destination key to the list of possible uploads? (@rynge)

**Comment by rynge** [comment]
Is it just a string? List?

**Comment by XeBoris** [comment]
Sorry, forgot to mention it! It is a list of strings.

**Comment by rynge** [comment]
I think this has been addressed. Can you give it a try?
